const Types = {
  SET_CALENDAR_MONTH: "SET_CALENDAR_MONTH",
  SET_SELECTED_DATE: "SET_SELECTED_DATE",
  OPEN_REMINDER_DIALOG: "OPEN_REMINDER_DIALOG",
  CLOSE_REMINDER_DIALOG: "CLOSE_REMINDER_DIALOG",
  CREATE_REMINDER: "CREATE_REMINDER",
  UPDATE_REMINDER: "UPDATE_REMINDER",
  DELETE_REMINDER: "DELETE_REMINDER",
  SET_CURRENT_REMINDER: "SET_CURRENT_REMINDER",
  REMOVE_CURRENT_REMINDER: "REMOVE_CURRENT_REMINDER"
};

export default Types;
